services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=vectordb'
      - 'POSTGRES_PASSWORD=testpwd'
      - 'POSTGRES_USER=testuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
